README.md

This updates all the links to Slack to our main link which is maintained to always redirect to an active link.

Updated slack links

---

README.md
cspell.config.json

This PR adds documentation on a frequently asked question about how "passthrough options" work with Connect-Query.

Add documentation for passthrough options

---

packages/connect-query/jest-environment-jsdom.js
packages/connect-query/package.json
packages/connect-query/tsup.config.ts

Convert all outputs to module by default and export commonjs as secondary.
Fixes #54

Compile both commonjs + esm

---

.github/workflows/ci.yaml
CONTRIBUTING.md
cspell.config.json
package.json

Using corepack should ensure that the correct versions are used.

Use corepack to guarantee pnpm version

---

README.md
examples/react/basic/package.json
examples/react/basic/src/gen/eliza-BigIntService_connectquery.ts
examples/react/basic/src/gen/eliza-ElizaService_connectquery.ts
examples/react/basic/src/gen/eliza-Haberdasher_connectquery.ts
examples/react/basic/src/gen/eliza-PaginatedService_connectquery.ts
examples/react/basic/src/gen/eliza-SecondService_connectquery.ts
examples/react/basic/src/gen/eliza-Slouch_connectquery.ts
package.json
packages/connect-query/src/create-hooks.ts
packages/connect-query/src/create-query-functions.test.ts
packages/connect-query/src/create-query-functions.ts
packages/connect-query/src/create-query-service.test.tsx
packages/connect-query/src/create-query-service.ts
packages/connect-query/src/create-unary-functions.test.ts
packages/connect-query/src/create-unary-functions.ts
packages/connect-query/src/create-unary-hooks.ts
packages/connect-query/src/index.ts
packages/connect-query/src/jest/test-utils.tsx
packages/connect-query/src/use-transport.test.tsx
packages/protoc-gen-connect-query-react/snapshots/gen/connectrpc/eliza/v1/eliza-ElizaService_connectquery_react.d.ts
packages/protoc-gen-connect-query-react/snapshots/gen/connectrpc/eliza/v1/eliza-ElizaService_connectquery_react.ts
packages/protoc-gen-connect-query-react/src/generateDts.ts
packages/protoc-gen-connect-query-react/src/generateTs.ts
packages/protoc-gen-connect-query/snapshots/gen/connectrpc/eliza/v1/eliza-ElizaService_connectquery.d.ts
packages/protoc-gen-connect-query/snapshots/gen/connectrpc/eliza/v1/eliza-ElizaService_connectquery.js
packages/protoc-gen-connect-query/snapshots/gen/connectrpc/eliza/v1/eliza-ElizaService_connectquery.ts
packages/protoc-gen-connect-query/src/generateDts.ts
packages/protoc-gen-connect-query/src/generateTs.ts

Less reliance on React specific APIs (in the core of connect-query) allows the core API to adapt better to scenarios like Server Components or other frameworks.
This PR keeps the existing plugin API (while adding some new methods) but frees us up to be more selective about the react APIs we NEED for other future plugins.
- Removed `UnaryHooks` type and replaced with `UnaryFunctionsWithHooks`
- Updated `createUnaryHooks` to only return the hooks and not other functions
Introduced `createUnaryFunctions` which can be used with the new `createUnaryHooks` to do the same thing as the old `createUnaryHooks`. The reasoning behind this change is to prep the core library, `connect-query`, to be able to used separately from React itself and this is just the first step in that direction.
Each service …

Extract React specific dependencies into single file

---

packages/protoc-gen-connect-query-react/snapshots/gen/connectrpc/eliza/v1/eliza-ElizaService_connectquery_react.ts
packages/protoc-gen-connect-query-react/src/generateTs.ts

The useXQuery methods cover these cases so we should only expose non-hooks through these exports.
The below API was never published so it's not a breaking change, just fixing generated `.ts` code to match what I had expected it to be.

Generate proper service methods without hooks

---

.github/workflows/ci.yaml
cspell.config.json
package.json
packages/connect-query/package.json
pnpm-lock.yaml
turbo.json

Fixes #182 
This integrates the `arethetypeswrong` CLI to the codebase and runs it in CI, fixing any type issues that existed.

Integrate `arethetypeswrong`

---

packages/connect-query/src/use-infinite-query.ts

Fixes #298 (again)
Missed another file. All these will automatically be caught once #186 is merged.

Missed adding .js to a few files

---

packages/connect-query/package.json

Fixes #305 
We don't need such a restrictive peer dependency. Anything in 5.x will do.

Loosen peer dependency requirement

---

packages/connect-query/package.json

Fixes #305 
For more details, see https://github.com/bufbuild/protobuf-es/issues/610 but the long story short is that module systems in nodejs/browser continue to hurt everyone involved.

Fix dual package hazard in nodejs

---

README.md

Since we're getting a lot of questions about using interceptors in connect-query, putting a small example inside the readme itself.

Add interceptor example to readme

---

packages/connect-query/src/use-query.test.ts
packages/connect-query/src/use-query.ts

Fixes #317 
Incoming queryOption should be taken into account for final enable status, just don't let it override the disableQuery input.

Make sure to take into account enabled queryOption

---

README.md
packages/connect-query/src/connect-query-key.ts
packages/connect-query/src/create-use-infinite-query-options.ts
packages/connect-query/src/index.ts
packages/connect-query/src/use-infinite-query.test.ts

Introduces a unique key for infinite queries so there's no chance to overlap and cause issues with shared cache.
This change introduces a new function and a new type:
- `ConnectInfiniteQueryKey` which is just the original `ConnectInfiniteQueryKey` with an added param to indicate it's for infinite queries
- `createConnectInifiniteQueryKey` which will create the above type.
This is technically a breaking change from a type perspective, though behaviour changes should be kept at a minimum since the key created by `createConnectQueryKey` will still work to invalidate infinite queries (unless the `exact` parameter is provided).
Fixes #328.

Add a distinguishing factor between infinite query keys and regular query keys

---

packages/connect-query/src/use-infinite-query.test.ts
packages/connect-query/src/use-infinite-query.ts

Porting support that was already added to `useQuery` in #318.
Fixes #336

Add support for enabled to useInfiniteQuery

---

packages/connect-query/src/create-use-infinite-query-options.ts
packages/connect-query/src/use-infinite-query.test.ts
packages/connect-query/src/use-infinite-query.ts

Remove unnecessary extends generics.
Fixes #342

Prevent using extendible input type

---

README.md
packages/connect-query/src/index.ts

Ideally we'd be able to create an opinionated version of `useQueries` but due to the complexity of those recursive types and there still being other queryClient methods that can benefit from these APIs, I propose we expose these internal APIs as helpers.
Fixes #333
Fixes #296

Expose internal methods used to create query options

---

.github/workflows/ci.yaml
packages/connect-query/src/use-mutation.test.ts
packages/connect-query/src/use-mutation.ts

Add missing generic so `onMutate` can pass additional context to success/failure handlers.

Need mutation context generic to support passing context

---

packages/connect-query/eliza.proto
packages/connect-query/src/connect-query-key.test.ts
packages/connect-query/src/connect-query-key.ts
packages/connect-query/src/gen/eliza_connect.ts
packages/connect-query/src/gen/eliza_pb.ts
packages/connect-query/src/jest/test-utils.tsx

With the current state, a generated key for a message with undefined fields and one with defined (but matching the default) fields will be different, meaning that duplicate requests can be made. This change ensures that all keys generated take into account default fields.
Fixes #361

Make sure generated keys include defaults

---

packages/connect-query/src/create-use-query-options.ts
packages/connect-query/src/use-query.test.ts
packages/connect-query/src/use-query.ts

Currently, tanstack's `useQuery` is always passed `false` or `true` for `enabled`. But if a user hasn't provided any explicit enablement, either using `disableQuery` or `queryOptions`, then the `QueryClient`'s default options should be used, which requires making sure `enabled` is unset, not an explicit boolean value.

Respect enabled:false in QueryClient's default options

---

packages/connect-query/README.md

Fixes #378 
This fixes the link to the examples directory and also removes the wording about 'various frameworks' since right now, we only show React and it's a bit misleading.

Fix link to examples

---

packages/protoc-gen-connect-query/README.md

With version 2 of [@bufbuild/protoplugin](https://www.npmjs.com/package/@bufbuild/protoplugin), standard plugin options have more convenient default behavior:
- [`import_extension`](#import_extension) is now `none` by default, which means we don't add a `.js` extension to import
paths. If you use the plugin option `import_extension=none`, you can delete it. If you require imports to have the `.js`
extension, use `import_extension=js`.
- [`ts_nocheck`](#ts_nochecktrue) is now off by default. If you require a `// @ts-nocheck` annotation at the top of
generated code, use `ts_nocheck=true`.

V2: Update documentation for plugin options import_extension and ts_nocheck

---

packages/connect-query/src/use-mutation.test.ts
packages/connect-query/src/use-mutation.ts

I noticed that `useMutation` accepts `CallOptions.signal`, but other hooks do not. This removes the option. 
I'm not sure why it would be desirable to cancel a mutation. If I'm missing something, please let me know.

V2: Remove option for AbortSignal from useMutation

---

packages/connect-query/src/use-infinite-query.ts
packages/connect-query/src/use-mutation.ts
packages/connect-query/src/use-query.ts

Parts of the API use JSDoc tags, but they are all outdated. That's worse than having no tags, so I propose we remove them.

Remove outdated JSDoc tags

---

packages/connect-query/src/call-unary-method.ts
packages/connect-query/src/use-mutation.ts

`callUnaryMethod` accepts `CallOptions` from `@connectrpc/connect`. This updates the implementation to support all options.

Honor all call options in callUnaryMethod

---

packages/connect-query/src/create-use-infinite-query-options.ts
packages/connect-query/src/create-use-query-options.ts
packages/connect-query/src/use-infinite-query.ts
packages/connect-query/src/use-query.ts

https://github.com/connectrpc/connect-query-es/pull/369 made a change to `useQuery` to support edge cases with the `enabled` option.
This makes the same change to the other query hooks.

V2: Support disabled queries consistently

---

README.md
packages/connect-query/src/call-unary-method.test.ts
packages/connect-query/src/call-unary-method.ts
packages/connect-query/src/create-use-infinite-query-options.ts
packages/connect-query/src/create-use-query-options.ts
packages/connect-query/src/use-infinite-query.ts
packages/connect-query/src/use-mutation.ts
packages/connect-query/src/use-query.ts

Hooks and several other functions accept [`CallOptions`](https://github.com/connectrpc/connect-es/blob/v1.5.0/packages/connect/src/call-options.ts#L21) from `@connectrpc/connect`. In general, every Connect client should accept a call options argument, but they don't work well with TanStack Query's caching. 
For now, we're removing `CallOptions` from the function arguments in v2.

V2: Remove CallOptions

---

packages/connect-query/src/transport-key.test.ts
packages/connect-query/src/transport-key.ts

As a potential solution for #418, this introduces a function to create a unique key per Transport reference. 
Going forward, we can use this function to create query keys that include the Transport.

V2: Introduce function to create transport keys

---

README.md
packages/connect-query/src/create-infinite-query-options.ts
packages/connect-query/src/create-query-options.test.ts
packages/connect-query/src/create-query-options.ts
packages/connect-query/src/index.ts
packages/connect-query/src/use-infinite-query.ts
packages/connect-query/src/use-query.ts

This renames functions and types to match their export names. For context, see https://github.com/connectrpc/connect-query-es/pull/436#discussion_r1786200957.
The first two commits rename symbols. The other commits co-locate the option types with their hooks and simplify them.

V2: Rename symbols to match exported names

---

examples/react/basic/package.json

Fixes #442 
The preview script doesn't make sense without a build step and `npm run dev` works fine enough to demo the functionality.

Remove preview script

---

README.md
packages/connect-query/src/call-unary-method.test.ts
packages/connect-query/src/connect-query-key.test.ts
packages/connect-query/src/connect-query-key.ts
packages/connect-query/src/create-infinite-query-options.ts
packages/connect-query/src/create-query-options.test.ts
packages/connect-query/src/create-query-options.ts
packages/connect-query/src/index.ts
packages/connect-query/src/message-key.test.ts
packages/connect-query/src/message-key.ts
packages/connect-query/src/use-infinite-query.test.ts
packages/connect-query/src/use-infinite-query.ts
packages/connect-query/src/use-query.test.ts

This changes the type for Connect query keys to be:
```ts
type ConnectQueryKey = [
/**
* To distinguish Connect query keys from other query keys, they always start with the string "connect-query".
*/
"connect-query",
{
/**
* A key for a Transport reference, created with createTransportKey().
*/
transport?: string;
/**
* The name of the service, e.g. connectrpc.eliza.v1.ElizaService
*/
serviceName: string;
/**
* The name of the method, e.g. Say.
*/
methodName?: string;
/**
* A key for the request message, created with createMessageKey(),
* or "skipped".
*/
input?: Record<string, unknown> | "skipped";
/**
* Whether this is an infinite query, or a regular one.
*/
cardinality?: "infinite" | "finite";
},
];
```
The function `createConnectQueryKey` is updated to accept key parameters as an …

V2: Update query keys for partial matching

---

.eslintrc.js
README.md
examples/react/basic/vite.config.ts
packages/connect-query/src/call-unary-method.test.ts
packages/connect-query/src/connect-query-key.test.ts
packages/connect-query/src/connect-query-key.ts
packages/connect-query/src/create-infinite-query-options.ts
packages/connect-query/src/create-query-options.test.ts
packages/connect-query/src/create-query-options.ts
packages/connect-query/src/index.ts
packages/connect-query/src/message-key.test.ts
packages/connect-query/src/message-key.ts
packages/connect-query/src/transport-key.test.ts
packages/connect-query/src/transport-key.ts
packages/connect-query/src/use-infinite-query.test.ts
packages/connect-query/src/use-infinite-query.ts
packages/connect-query/src/use-query.test.ts
packages/connect-query/src/use-transport.tsx
packages/connect-query/vite.config.ts

This adds a function that can apply a static key to a transport, useful when considering SSR contexts where the transport on the client is not the same transport as on the server.

V2: Add utility to support explicit key on transport

---

README.md
packages/connect-query/src/utils.test.ts
packages/connect-query/src/utils.ts

Closes #446. The signature of the provided updater function is changed to return a message instead of a message init shape.

V2: Update createProtobufSafeUpdater

---

README.md
packages/connect-query/src/call-unary-method.test.ts
packages/connect-query/src/connect-query-key.test.ts
packages/connect-query/src/connect-query-key.ts
packages/connect-query/src/create-query-options.test.ts
packages/connect-query/src/create-query-options.ts
packages/connect-query/src/use-infinite-query.test.ts

As discussed in [discussion thread](https://github.com/connectrpc/connect-query-es/pull/449#discussion_r1793551960), we need to be explicit about cardinality of query keys.

V2: Enforce cardinality as required prop for key

---

.github/RELEASING.md
scripts/release.mjs

This ports the script we use for connect-es and protobuf-es for pnpm. When publishing with this script, the dist-tag is determined from the version, and can't be forgotten.

Add script to guard against publishing with the wrong dist-tag

---

.eslintrc.js
packages/connect-query/src/create-query-options.test.ts
packages/connect-query/src/create-query-options.ts

In order to use createQueryOptions with recent versions of react-query and `useSuspenseQuery`, we need to make sure createQueryOptions isn't passing `skipToken` as a potential type when the input type couldn't be skipToken. This is because the typings for `useSuspenseQuery` now disallow skipping (which was always the case, just was not reflected in the types.)
To fix this, we overload the `createQueryOptions` call to indicate with it's types that it will only return a skipToken when input is a skipToken.

V2: Add overload to make sure createQueryOptions only returns skipToken when could be passed skipToken

---

packages/connect-query/src/create-infinite-query-options.ts

If we customize the queryKeyHashFn, it prevents `queryClient.setQueryData` from finding the query in question, unless the `queryClient` was initialized with the same queryKeyHashFn. It would be nice to be able to customize this on a per query basis but [it doesn't seem to be an accepted approach](https://github.com/TanStack/query/issues/2352#issuecomment-2422530700).

V2: Remove queryKeyHashFn to allow default query client access to queries

---

packages/connect-query-core/src/create-infinite-query-options.test.ts
packages/connect-query-core/src/create-infinite-query-options.ts
packages/connect-query/src/use-infinite-query.test.ts

Similar to #469 , we need to overload createInfiniteQueryOptions so it can work with suspense variants of the most recent version of react-query.

Fix createinfinitequeryoptions skiptoken usage

---

README.md

This adds a note at the top of the README:
> [!IMPORTANT]  
> You are looking at the release candidate for version 2. For the current stable version, see the branch [v1](https://github.com/connectrpc/connect-query-es/tree/v1).
The plan is to switch the main branch to v2, same as https://github.com/connectrpc/connect-es/pull/1295 and https://github.com/connectrpc/examples-es/pull/2040.
The actual switch is currently blocked by https://github.com/connectrpc/connect-query-es/pull/475.

V2: Prepare switch to v2

---

README.md
packages/examples/react/basic/src/example.tsx

To better reflect real world scenarios, it makes sense to include the payload even if it might not be necessary.

Updated basic example to include payload

---

.github/CONTRIBUTING.md
.github/RELEASING.md

To better match the release process with connect-es. Left the examples specifically pointing at connect-es tag since we don't really have a good example in connect-query-es.

Match release process with connect-es

---

cspell.config.json

Leaving these causes lint to fail if running concurrently with tests.

Ignore vitest generated files in spell checking

---

.gitignore
README.md
package-lock.json
packages/connect-query-core/package.json
packages/connect-query-core/src/connect-query-key.test.ts
packages/connect-query-core/src/connect-query-key.ts
packages/connect-query-core/src/create-infinite-query-options.ts
packages/connect-query-core/src/create-query-options.ts
packages/connect-query-core/src/utils.ts
packages/connect-query/package.json
packages/connect-query/src/use-infinite-query.ts
packages/connect-query/src/use-query.ts

By adding DataTag annotations to the ConnectQueryKey, QueryClient methods can now infer the return type when calling things like `getQueryData` or `invalidateQueries`.
This is at least a partial alternative to #468 which provides better inference abilities while keeping our api surface smaller. There may still be value down the line with very well defined query client methods but I suspect this change covers 90% of the current use cases.

Add datatag to ConnectQueryKey so queryClient can infer type info
